version: "3.8"

services:
  ticker:
    build:
      context: .
    devices:
      - "/dev/mem:/dev/mem"
    privileged: true
    restart: always
    env_file:
      - ./settings.env
    volumes:
      - .:/code
